name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

    # Uncomment the following steps when you're ready to build and deploy
    # - name: Build and deploy
    #   run: |
    #     npm run build
    #     npm run pm2:start
