name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build and deploy
        run: |
          npm run build
          npm run pm2:start  # Command to start your PM2-managed application
